return {
  { "catppuccin/nvim", name = "catppuccin" },
  { "Everblush/nvim", name = "everblush" },
  {"marciomazza/vim-brogrammer-theme"},
  {"ellisonleao/gruvbox.nvim"},
  {"neanias/everforest-nvim"},
  {"olimorris/onedarkpro.nvim"},
  {"EdenEast/nightfox.nvim"},
  {"folke/tokyonight.nvim"},
  {"rebelot/kanagawa.nvim"},
  {"shaunsingh/nord.nvim"},
  {"AlexvZyl/nordic.nvim"},
  {"Mofiqul/dracula.nvim"},
  {"rmehri01/onenord.nvim"},
  {"tiagovla/tokyodark.nvim"},
  {"loctvl842/monokai-pro.nvim"},
  {"xero/miasma.nvim"},
  {"mhartington/oceanic-next"},
  {"LunarVim/horizon.nvim"},
  {"miikanissi/modus-themes.nvim"},
  {"rafamadriz/neon"},
}
